use museu3;
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ademar Murad','1931','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Afrânio Montemurro','1943','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Akiko Fujita','1973','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Alexandre Coco','1939','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Alexandre Tiago da Silva','1946','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Alícia G Rossi','1937','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Amélia Luiza Simon','1932','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ana Alice Francisquetti','1941','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ana Kalassa el Banat','1941','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Anatol Wladyslaw','1976','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('André Lousas','1954','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Andreia Cristina Dulianel','1937','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Anna Maria Badaró','1975','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Antonio Carlos Rodrigues (TUNEU)','1966','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Antônio Henrique Amaral','1946','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Antônio Roseno de Lima','1964','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Arlindo Ferreira Gonçalves Dias Jr','1950','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Armando Vieira Filho','1942','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Axl Lescoschek','1944','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Beatriz Basile da Silva Rauscher','1958','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Berenice H. V. de Toledo','1945','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Bernardo Caro','1947','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Carolina B. Ribeiro','1940','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Carusto Camargo','1949','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Chico Machado','1943','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Cláudio Luiz Garcia','1934','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Cláudio Trintade','1969','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Clodomiro R Lucas Filho','1931','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Darcy Cruz','1934','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Dimas Planas Garcia','1975','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Dulce Barata','1949','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Edoardo Belgrado','1973','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Egas Francisco','1948','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Eleonora Fabre','1971','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Eliana Saldanha','1939','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ellen Banks','1947','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Enéas Dedecca','1934','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ermelindo Nardin','1949','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ernesto Bonato','1933','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Fabiana de Barros','1977','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Fábio Bittencourt','1930','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Fernando Gómez Alvarez','1969','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Fernando Manuel C. Durão','1946','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Flávio Alberto','1957','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Flemming Iorgensen','1951','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Francisco Biojone','1972','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Franco Sacchi','1959','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Fúlvia Gonçalves','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Gastão M. Henrique','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('George Rembrandt Gutlich','1965','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Geraldo de Barros','1959','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Geraldo de Souza','1941','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Geraldo Jurgensen','1944','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Geraldo Porto','1979','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Gerson Fogaça','1947','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Gilberto Prado','1966','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Gilmar Bartolo','1934','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Gino Bruno','1966','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Habuba Farah Ricetti','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Hércules Barsotti','1944','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Hermelindo Fiaminghi','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ivanir Cozeniosque Silva','1966','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Jerônimo Noboru Ohnuma','1938','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('João Batista Costa Aguiar','1932','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('João Cunha','1939','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('João Magalhães','1950','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('João Proteti','1953','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('José de Castro Mendes','1947','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('José de Souza de Oliveira Filho (Macaparama)','1945','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('José dos Santos Laranjeira','1964','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('José Mário A. Toledo','1980','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('José Roberto Zanellato','1963','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Josephine Coy','1957','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Lasar Segall','1971','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Léo Augustus Caraffa','1947','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Lúcia Fonseca','1961','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Luciana Idehara','1963','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Lucy Salles','1949','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Luis Guilherme Werneck Paiva','1979','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Luise Weiss','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Lygia Arcui Eluf e outros','1942','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Lygia Arcuri Eluf','1933','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Maciej Antoni Babinski','1943','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mara Ferraro','1945','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marcello Grassmann','1950','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marcelo Moscheta','1967','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Márcia Bortoletto','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Márcia Tomasi Novaes','1963','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Márcio Périgo','1979','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marco do Valle','1934','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marco Francisco Buti','1938','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Maria Ap. B. de Mello','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Maria do Céu D.de Oliveira','1953','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Maria Helena Motta Paes','1969','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Maria Leonarda A.Botelho','1949','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mariângela Ragassi','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mariene dos Santos','1975','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marilda Bernardes','1948','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mário Bueno','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mário da Silva','1951','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Marta Strambi','1972','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Mauricius Farina','1950','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Odilla Mestriner','1935','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Paula Almozara','1931','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Paulo Bruscky e Daniel Santiago','1957','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Paulo Costa','1955','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Paulo de Tarso Cheida Sans','1950','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Paulo de Tarso Coutinho','1971','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Percy Lau','1973','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Raul Porto','1976','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Reinaldo Bianchi Netto','1959','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Renina Katz','1942','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Ricardo Frantz','1940','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Rioji Koie','1943','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Roberto Keppler','1979','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Rogério da Silva Oliveira','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Sebastião Guimarães','1956','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Sergio Niculitcheff','1943','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Siegbert Franklin','1957','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Sônia Von Brusky','1964','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Suely Pinotti','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Suzana Lima','1948','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Suzie Signori','1972','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Thomáz Perina','1946','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Vanderlei Zalocchi','1978','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Vânia Mignone','1932','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Vera Bonnemasou','1931','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Waldomiro de Deus','1961','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Wladimir Fera','1932','0','Sem dados','Sem dados');
insert into ARTISTA (NOME,DATA_NASC,DATA_FALESC,ORIGEM,BIO) values ('Zandra Coelho de Miranda','1933','0','Sem dados','Sem dados');
