USE museu3;
   
CREATE TABLE ESTILO (
    ID_ESTILO			INT  AUTO_INCREMENT,
    INICIO				INT ,
    FIM					INT ,
    NOME				VARCHAR(50) ,
    DESCRICAO			VARCHAR(100) ,
    
    PRIMARY KEY (ID_ESTILO)
    );
    
CREATE TABLE ARTISTA (
    ID_ARTISTA			INT  AUTO_INCREMENT,
    NOME				VARCHAR(50) ,
    DATA_NASC			INT,
    DATA_FALESC			INT,
    ORIGEM				VARCHAR(50) ,
    BIO					VARCHAR(200),
    
    PRIMARY KEY (ID_ARTISTA)
    );
    
CREATE TABLE OBRA (
    ID_OBRA				INT  AUTO_INCREMENT,
    ID_ESTILO			INT ,
    TITULO				VARCHAR(50) ,
    DATA				INT ,
    DESCRICAO			VARCHAR(100) ,
    TAGS				VARCHAR(50) ,
    PATH_IMAGEM			VARCHAR(100),
    
    PRIMARY KEY (ID_OBRA),
    
    FOREIGN KEY (ID_ESTILO)
        REFERENCES ESTILO (ID_ESTILO)
    );
    
CREATE TABLE ESCULTURA (
    ID_OBRA				INT ,
    MATERIAIS			VARCHAR(50) ,
    ALTURA				NUMERIC(8,2) ,
    LARGURA				NUMERIC(8,2) ,
    PROFUNDIDADE		NUMERIC(8,2) ,
    
    PRIMARY KEY (ID_OBRA),
    
    FOREIGN KEY (ID_OBRA)
        REFERENCES OBRA (ID_OBRA)
    );
    
CREATE TABLE PINTURA (
    ID_OBRA				INT ,
    MATERIAIS			VARCHAR(50) ,
    ALTURA				NUMERIC(6,2) ,
    LARGURA				NUMERIC(6,2) ,
    
    PRIMARY KEY (ID_OBRA),
    
    FOREIGN KEY (ID_OBRA)
        REFERENCES OBRA (ID_OBRA)
    );
    
CREATE TABLE AUDIOVISUAL (
    ID_OBRA		        INT ,
    TIPO_MIDIA		    CHAR(10) ,
    
    PRIMARY KEY (ID_OBRA),
    
    FOREIGN KEY (ID_OBRA)
        REFERENCES OBRA (ID_OBRA)
    );
    
CREATE TABLE OBRA_ARTISTA (
    ID_OBRA				INT ,
    ID_ARTISTA			INT ,
    
    PRIMARY KEY (ID_OBRA, ID_ARTISTA),
    
    FOREIGN KEY (ID_OBRA)
        REFERENCES OBRA (ID_OBRA),
    
    FOREIGN KEY (ID_ARTISTA)
        REFERENCES ARTISTA (ID_ARTISTA)
    );
    
CREATE TABLE MUSEU (
    ID_MUSEU			INT  AUTO_INCREMENT,
    NOME				VARCHAR(50) ,
    CONTATO				VARCHAR(50) ,
    
    PRIMARY KEY (ID_MUSEU)
    );
    
CREATE TABLE CURADOR (
    ID_CURADOR			INT  AUTO_INCREMENT,
    NOME				VARCHAR(50) ,
    CONTATO				VARCHAR(50) ,
    
    PRIMARY KEY (ID_CURADOR)
    );
    
CREATE TABLE EXPOSICAO (
    ID_EXPOSICAO		INT  AUTO_INCREMENT,
    ID_CURADOR			INT ,
    ID_MUSEU			INT ,
    NOME				VARCHAR(50) ,
    DESCRICAO			VARCHAR(100) ,
    DATA_INICIO			DATETIME ,
    DATA_FIM			DATETIME ,
    STATUS_CD			CHAR(1),
    
    PRIMARY KEY (ID_EXPOSICAO),
    
    FOREIGN KEY (ID_CURADOR)
        REFERENCES CURADOR (ID_CURADOR),
    
    FOREIGN KEY (ID_MUSEU)
        REFERENCES MUSEU (ID_MUSEU)
    );

CREATE TABLE OBRA_EXPO (
    ID_OBRA				INT ,
    ID_EXPOSICAO		INT ,
    
    PRIMARY KEY (ID_OBRA, ID_EXPOSICAO),
    
    FOREIGN KEY (ID_OBRA)
        REFERENCES OBRA (ID_OBRA),
        
    FOREIGN KEY (ID_EXPOSICAO)
        REFERENCES EXPOSICAO (ID_EXPOSICAO)
    );

CREATE TABLE LOCAL (
    ZIP_CODE			CHAR(12) ,
    ID_MUSEU			INT ,
    ENDERECO			VARCHAR(100) ,
    CIDADE				VARCHAR(30) ,
    ESTADO				VARCHAR(30) ,
    PAIS				VARCHAR(30) ,
    
    PRIMARY KEY (ZIP_CODE, ID_MUSEU),
    
    FOREIGN KEY (ID_MUSEU)
        REFERENCES MUSEU (ID_MUSEU)
    );
